### ISSUE TITLE
定时任务并发问题

### ISSUE THREAD

**Issue by hcxiaoliu** [Panlf/springboot-task-scheduled#1]
想探讨一个问题
比如：现在数据库里有几十万会员（会员可能越来越多），不管用户在不在线，我想在每天中午十二点的时候定时给他们送10颗豆子，当天内不管用户什么时间登陆，就可以看到有一条记录，系统在12：01赠送了10颗豆子（就比如，我现在十二点在线的时候，刚好到了十二点过一分，系统就自动送了我10颗豆子），怎样能保证这个时间的准确性。以及每个用户都能插入这个10颗豆子
求思路

**Comment by Panlf** [comment]
这个问题因为是不同会员在同一时间得到10颗豆子，线程安全问题影响不大，主要是短时间内需要多次操作数据库，我觉得可以使用多线程批量插入这10豆子，但是会员那么多，非常耗性能。真要这1分钟全部插入可能需要分布式、分库、多线程结合。还有一种投机的方法就是在线的可以12：01之前插入，其他的可以慢慢插入。我感觉你这个问题可以简化为1分钟内进行几十万次的数据插入，我是这样觉得，希望能帮到你。

> 想探讨一个问题
> 比如：现在数据库里有几十万会员（会员可能越来越多），不管用户在不在线，我想在每天中午十二点的时候定时给他们送10颗豆子，当天内不管用户什么时间登陆，就可以看到有一条记录，系统在12：01赠送了10颗豆子（就比如，我现在十二点在线的时候，刚好到了十二点过一分，系统就自动送了我10颗豆子），怎样能保证这个时间的准确性。以及每个用户都能插入这个10颗豆子
> 求思路

这个问题因为是不同会员在同一时间得到10颗豆子，线程安全问题影响不大，主要是短时间内需要多次操作数据库，我觉得可以使用多线程批量插入这10豆子，但是会员那么多，非常耗性能。真要这1分钟全部插入可能需要分布式、分库、多线程结合。还有一种投机的方法就是在线的可以12：01之前插入，其他的可以慢慢插入。我感觉你这个问题可以简化为1分钟内进行几十万次的数据插入，我是这样觉得，希望能帮到你。

**Comment by Panlf** [comment]
这个问题因为是不同会员在同一时间得到10颗豆子，线程安全问题影响不大，主要是短时间内需要多次操作数据库，我觉得可以使用多线程批量插入这10豆子，但是会员那么多，非常耗性能。真要这1分钟全部插入可能需要分布式、分库、多线程结合。还有一种投机的方法就是在线的可以12：01之前插入，其他的可以慢慢插入。我感觉你这个问题可以简化为1分钟内进行几十万次的数据插入，我是这样觉得，希望能帮到你。
