### ISSUE TITLE
任务删除的疑问

### ISSUE THREAD

**Issue by 231771258** [Panlf/springboot-task-scheduled#2]
你好！

为什么MapContainer 中的deleteMap只删除了map中的实例，没有把数据库中的数据删掉呢？

**Comment by Panlf** [comment]
> 你好！
> 
> 为什么MapContainer 中的deleteMap只删除了map中的实例，没有把数据库中的数据删掉呢？

你可以看一下CronService类，里面是所有的逻辑操作，MapContainer是一个容器，只存储正在运行的定时任务，数据库操作是在CronService类中的，然后我数据库是逻辑删除，就是status为0是已删除的，1是正在运行的，2是暂停的。其实这个项目思路是很简单的，就是需要运行的定时任务放在MapContainer中运行，其他状态都是不在MapContainer中的，数据库是保存着每个定时任务的状态（运行、暂停、已删除）。
